### PR TITLE
Derive CommandLabel from the commands and use it to type clickToolbar

### PR DESCRIPTION
**Pull request by raineorshine**
Follows #5001, which merged while this was in progress — this now targets `main` directly.

`clickToolbar` took `label: string`, so a typo or a renamed command surfaced as a selector timeout rather than a type error.

### The union is derived, not listed

Same shape as the existing `CommandId`, which is `keyof typeof commands`:

```ts
type CommandLabel = (typeof commands)[keyof typeof commands]['label']
```

Nothing repeats what the commands already declare. Adding a command extends the type; renaming a label breaks the call sites that used the old one.

### What had to change to make that possible

The `: Command` annotation was discarding the information — it types the constant as the interface and throws away what the object says about itself. The 84 commands now use `satisfies Command`, which checks against the interface while keeping the inferred type.

`satisfies` alone turned out **not** to be enough for the label: the interface types it as `string`, and that contextual type widens the literal anyway. I verified this empirically rather than assuming — of the four variants I tried (`satisfies` alone, `as const` on the label, an identity helper with a `const` type parameter, and a plain generic helper), only the middle two preserve the literal. `as const` on the label is the one that doesn't disturb any other inference; the `const` type parameter would infer readonly tuples for the literal `keyboard`/`gesture` arrays in 37 commands and violate the constraint.

`headings.ts` builds its six commands through a factory that returned `Command`, widening all six labels and collapsing the union on its own. It is now generic over the level. Its description moved out to a function typed on `HeadingLevel`, since the factory's generic level cannot be narrowed enough to index `headingLabels`.

### The silent failure mode is guarded

A command that skips either `satisfies` or `as const` widens its label to `string`, which collapses the entire union and turns every `CommandLabel` annotation back into a plain `string` — with nothing to signal it. `src/@types/__tests__/CommandLabel.ts` asserts at compile time that it hasn't happened:

```
error TS2322: Type 'true' is not assignable to type
'a command label widened to string: declare the command with `satisfies Command` and its label `as const`'.
```

I confirmed that by widening a label and watching it fire, then restoring it — the guard is not vacuous.

### Two consequences worth flagging

- `satisfies` infers each command's *real* signatures rather than the interface's, so a direct call like `command.exec(dispatch, getState, e, { type })` no longer typechecks against an implementation that declares no parameters. Only `commands/__tests__/navigate.ts` did this; its calls are now `exec()` and `canExecute()`, which also drops four `as never` casts. Everything else reaches commands through `commandById`, which returns `Command`, and is unaffected.
- Typing the parameter proved every existing `clickToolbar` call site names a real command — `tsc` passing is that check.

### Verification

`tsc`, `eslint`, and `prettier` clean. Unit suite: 1886 passed. Two files timed out at 5000ms under full-suite load and passed in isolation, and the failing set differed between runs — load flakiness, not this change; CI is the arbiter. Puppeteer smoke: `letterCase`, `sort`, `format` (9 tests). `docs/commands.md` documents the idiom and why it's load-bearing.

### Not done

`svg` is optional on `Command`, and 7 of 84 commands lack it — they cannot be toolbar buttons at all (`ToolbarButton` logs an error and bails). `clickToolbar` could narrow further to just the toolbar-capable labels. Left out as a separate judgment call rather than folded in here.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by raineorshine** [comment]
Added the `skip-tdd-unit` label, so flagging why rather than leaving it as a silent bypass.

The TDD workflow checked out `src/@types/__tests__/CommandLabel.ts` onto `main` and ran it, expecting a failure. It passed in 2ms:

```
✓ unit src/@types/__tests__/CommandLabel.ts (1 test) 2ms
❌ TDD flagged: changed tests PASS on the base branch.
```

That is the correct behavior for this test rather than a hole in it. Every assertion in it is compile-time — `expectTypeOf` is a no-op at runtime, and the `string extends CommandLabel ? ... : true` guard is erased along with the type-only import of `../CommandLabel`. What survives into the runtime test body is `expect(true).toBe(true)`, which passes anywhere, on any branch. The enforcement lives in `tsc`, which the Lint check runs — and that is where the guard actually fires, as shown in the PR description.

So there is no version of this test that fails on `main` at runtime, which is what the label's description covers ("you expect the new unit tests to pass on main"). It follows the existing precedent for type assertions in `src/util/__tests__/storage.ts`.

Every other check is green, including the full unit suite and Puppeteer.

**Comment by raineorshine** [comment]
Replaced the `skip-tdd-unit` label with a design that doesn't need it, and removed the label.

The guard was a vitest test whose assertions were all compile-time, so it passed on `main` and TDD flagged it. Labeling around that turned out to be impossible anyway — the workflow reads labels from `github.event.pull_request.labels`, and its only trigger is `pull_request` with the default types, so a re-run replays the pre-label payload and a label alone never fires a fresh one. That was worth discovering, because the label was the wrong fix regardless: the test contributed nothing at runtime, and every future PR touching it would have tripped the same gate.

The assertion now lives in the type it guards:

```ts
type CommandLabel = string extends Labels
  ? 'a command label widened to string: declare the command with `satisfies Command` and its label `as const`'
  : Labels
```

Enforcement is unchanged — it was always `tsc`, never vitest — but the failure is now louder rather than quieter. Widening a label reports it at every call site that passes one, with the fix in the message:

```
error TS2345: Argument of type '"Text Color"' is not assignable to parameter of type
'a command label widened to string: declare the command with `satisfies Command` and its label `as const`'.
```

Verified by widening `bold`'s label and restoring it. `src/@types/CommandLabel.ts` stays a pure type module alongside `CommandId.ts`, there is no changed test file, and TDD now has nothing to detect.
